-- Disable ALL RLS on ALL tables
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE players DISABLE ROW LEVEL SECURITY;
ALTER TABLE matches DISABLE ROW LEVEL SECURITY;
ALTER TABLE news_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE team_documents DISABLE ROW LEVEL SECURITY;
